# audit-policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["configmaps"]
  - level: Metadata
    resources:
    - group: ""
      resources: ["secrets"]
  - level: Metadata
    verbs: ["get", "list", "watch"]
